import { CalendarEntry, AgentLog, MetricCard } from "./types";

export const CREATOR_TYPES = [
  "Music",
  "Anime",
  "Quotes",
  "Motivation",
  "Business",
  "Gym",
  "Travel",
  "Fashion",
  "Finance",
  "Technology",
  "Education",
  "Gaming",
  "Lifestyle",
];

export const PLATFORMS = [
  "Instagram",
  "TikTok",
  "YouTube Shorts",
  "Facebook",
  "LinkedIn",
  "Pinterest",
  "Threads",
];

export const GOALS = [
  "More Followers",
  "More Reach",
  "More Revenue",
  "Affiliate Sales",
  "Brand Deals",
  "Personal Brand",
];

export const INITIAL_METRICS: MetricCard[] = [
  {
    id: "followers",
    label: "Total Followers",
    value: "148.4K",
    change: "+4.2%",
    isPositive: true,
    trend: [30, 40, 35, 50, 49, 60, 70, 85],
  },
  {
    id: "views",
    label: "Video Views (30d)",
    value: "1.82M",
    change: "+28.1%",
    isPositive: true,
    trend: [20, 30, 45, 40, 55, 75, 68, 92],
  },
  {
    id: "reach",
    label: "Account Reach",
    value: "1.14M",
    change: "+34.5%",
    isPositive: true,
    trend: [10, 15, 22, 35, 30, 45, 52, 65],
  },
  {
    id: "watch_time",
    label: "Watch Time (hrs)",
    value: "32.1K",
    change: "+12.4%",
    isPositive: true,
    trend: [40, 45, 42, 50, 48, 52, 55, 58],
  },
  {
    id: "revenue",
    label: "Projected Revenue",
    value: "$4,812.50",
    change: "+18.9%",
    isPositive: true,
    trend: [15, 20, 25, 22, 30, 35, 38, 48],
  },
  {
    id: "engagement",
    label: "Avg Engagement",
    value: "5.82%",
    change: "-0.4%",
    isPositive: false,
    trend: [6.2, 6.1, 6.0, 5.9, 5.8, 5.9, 5.85, 5.82],
  },
  {
    id: "scheduled",
    label: "Scheduled Posts",
    value: "18",
    change: "Next: Today 6PM",
    isPositive: true,
    trend: [12, 14, 15, 16, 17, 18, 18, 18],
  },
  {
    id: "decisions",
    label: "AI Actions (Today)",
    value: "1,248",
    change: "Autonomous Mode",
    isPositive: true,
    trend: [800, 950, 1100, 1150, 1200, 1248, 1248, 1248],
  },
];

export const INITIAL_LOGS: AgentLog[] = [
  {
    id: "log-1",
    timestamp: "07:11:02",
    text: "Trend Hunter scanning global Reddit r/audiophile & TikTok Soundboard...",
    agentId: "trend_hunter",
    status: "running",
  },
  {
    id: "log-2",
    timestamp: "07:05:41",
    text: "AI CEO synthesized morning performance briefing.",
    agentId: "ai_ceo",
    status: "success",
  },
  {
    id: "log-3",
    timestamp: "06:42:15",
    text: "Learning Agent detected +62% spike in Rain-themed cinematic videos on TikTok.",
    agentId: "learning_agent",
    status: "warning",
  },
  {
    id: "log-4",
    timestamp: "06:00:00",
    text: "AI Studio successfully rendered subtitle timing for Draft Reels #4 & #5.",
    agentId: "ai_studio",
    status: "success",
  },
  {
    id: "log-5",
    timestamp: "05:30:12",
    text: "Competitor Intelligence completed OSINT scrap on top 5 niche benchmarks.",
    agentId: "competitor_intel",
    status: "success",
  },
];

export const INITIAL_CALENDAR: CalendarEntry[] = [
  {
    day: 1,
    time: "12:00 PM",
    topic: "The Hidden Tax on Solopreneur Success",
    format: "Instagram Reel",
    mixType: "Educational / Authority",
    description: "Start with an ultra-short 1.2s B-roll clip of pouring high-end coffee in a dark mug. Overlay caption: 'Nobody fails because they lack strategy.' Target high curiosity gap.",
    status: "published",
  },
  {
    day: 2,
    time: "6:30 PM",
    topic: "3 AI Rules to Automate Your Side-Hustle",
    format: "TikTok Short",
    mixType: "Viral Hook",
    description: "Fingers clicking keyboard on a sleek mechanical setup, transition to screen recording of automated script triggers. Energetic deep ambient synth audio.",
    status: "published",
  },
  {
    day: 3,
    time: "12:00 PM",
    topic: "Why I Swear by 4AM Deep Work Blocks",
    format: "YouTube Short",
    mixType: "Storytelling / Personal Brand",
    description: "Stark dark workspace illuminated by a single warm orange monitor light bar. Highlight productivity hacks and quiet hours benefits.",
    status: "scheduled",
  },
  {
    day: 4,
    time: "6:30 PM",
    topic: "Building the AI OS in Public: Sneak Peek",
    format: "Instagram Reel",
    mixType: "Viral Hook / Product",
    description: "Showing the slick design interface of CreatorOS AI running autonomous agents in real time. Dynamic overlays.",
    status: "draft",
  },
  {
    day: 5,
    time: "1:00 PM",
    topic: "A Warning to All Traditional Video Editors...",
    format: "TikTok Short",
    mixType: "Authority / Polarizing",
    description: "Stark facial close-up with dramatic split lighting. Discussion on how autonomous beat-matching models render manual clips legacy.",
    status: "draft",
  },
];

export const AGENT_CARDS_INFO = [
  {
    id: "trend_hunter",
    name: "Trend Hunter",
    role: "Niche Analyst & Viral Spotter",
    description: "Scans global channels (TikTok, X, Reddit, YT Shorts) for audio, hooks, and hashtags before they reach the mainstream.",
    avatarColor: "from-purple-500 to-indigo-600",
    defaultPrompt: "Business & Productivity",
  },
  {
    id: "content_planner",
    name: "Content Planner",
    role: "Strategic Content Architect",
    description: "Generates high-conversion 30-day schedules, series ideas, growth roadmap road blocks, and schedules posting times.",
    avatarColor: "from-blue-500 to-indigo-500",
    defaultPrompt: "Lifestyle & Fitness Content",
  },
  {
    id: "visual_finder",
    name: "Visual Finder",
    role: "Cinematic Scene Searcher",
    description: "Bridges music themes and clips to fetch perfect b-roll suggestions, anime clips, nature drone shots, or cyberpunk aesthetics.",
    avatarColor: "from-indigo-500 to-cyan-500",
    defaultPrompt: "Cyberpunk rain with lo-fi beats",
  },
  {
    id: "thumbnail_generator",
    name: "Thumbnail Generator",
    role: "High-CTR Visual Hook Designer",
    description: "Designs thumbnail concepts, text overlays, and visual hierarchy ideas that improve click-through from stagnant profiles.",
    avatarColor: "from-orange-500 to-rose-500",
    defaultPrompt: "Create thumbnail concepts for a motivational reel about consistency",
  },
  {
    id: "publisher",
    name: "Publisher",
    role: "Autonomous Post Dispatcher",
    description: "Reads the approved calendar, schedules posts, and coordinates the final content release flow across connected channels.",
    avatarColor: "from-emerald-500 to-lime-500",
    defaultPrompt: "Schedule the next outreach posts for a business creator",
  },
  {
    id: "ai_studio",
    name: "AI Studio",
    role: "Video & Transition Editor",
    description: "Automatically matches beats, overlays subtitle timings, generates captions, renders thumbnail drafts, and automates publishing.",
    avatarColor: "from-pink-500 to-purple-600",
    defaultPrompt: "Automate transition rendering",
  },
  {
    id: "caption_writer",
    name: "Caption Agent",
    role: "Viral Copywriter",
    description: "Drafts 6 distinct styled captions (Luxury, Emotional, Funny, Dark, Minimal, Storytelling) with specific CTAs.",
    avatarColor: "from-teal-400 to-emerald-500",
    defaultPrompt: "A lesson about taking action when you feel unready",
  },
  {
    id: "hashtag_generator",
    name: "Hashtag Agent",
    role: "SEO Growth Optimizer",
    description: "Generates a tactical mix of low, medium, trending, and evergreen hashtags designed for high discoverability.",
    avatarColor: "from-amber-400 to-orange-500",
    defaultPrompt: "Eaesthetic dark home setup workspace",
  },
  {
    id: "competitor_intelligence",
    name: "Competitor Intelligence",
    role: "Niche OSINT Expert",
    description: "Analyzes competitor engagement rates, outlier reels, hashtag strategies, weaknesses, and builds strategic counters.",
    avatarColor: "from-red-500 to-pink-500",
    defaultPrompt: "@visual_architect",
  },
  {
    id: "performance_analytics",
    name: "Performance Analyst",
    role: "Business Analytics Auditor",
    description: "Monitors metric health, audience retention curves, viral spikes, and projects revenue gains across social profiles.",
    avatarColor: "from-green-500 to-emerald-600",
    defaultPrompt: "Evaluate last 30 days reach surge",
  },
  {
    id: "learning_agent",
    name: "Learning Agent",
    role: "SaaS Core Engine Brain",
    description: "Continuously learns from real-time performance analytics. Feeds insights back to the planner, restructuring workflows.",
    avatarColor: "from-cyan-400 to-blue-600",
    defaultPrompt: "Auto-optimize posting strategy",
  },
  {
    id: "ai_ceo",
    name: "AI CEO",
    role: "Executive General Manager",
    description: "Combines overall agent telemetry to deliver your daily briefing, business logs, expected reach metrics, and tasks.",
    avatarColor: "from-violet-600 to-pink-600",
    defaultPrompt: "Autonomous Workspace Director",
  },
];
